name: CI
on: [push, pull_request]
env:
  CI: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Find yarn cache
        id: find-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: git checkout
        uses: actions/checkout@v2
      - name: Cache yarn dependencies
        uses: actions/cache@v1
        with:
          path: ${{steps.find-yarn-cache.outputs.dir}}
          key: ${{runner.os}}-node${{matrix.node-version}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: ${{runner.os}}-node${{matrix.node-version}}-yarn-
      - name: Set up Node.js v${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: yarn
      - run: yarn test
      - name: Upload build output
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: .
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    needs: build-and-test
#    steps:
#      - name: Download build output
#        uses: actions/download-artifact@v1
#        with:
#          name: build-output
#      - run: yarn semantic-release
#        working-directory: build-output
